figure(2)
x = -5:.01:500;
beta = 1;
gam = 1;
delta = 0;
plot( x , stblpdf(x,.5,beta,gam,delta,'quick'),...
  x , stblpdf(x,.75,beta,gam,delta,'quick'),...
  x , stblpdf(x,1,beta,gam,delta,'quick'),...
  x , stblpdf(x,1.25,beta,gam,delta,'quick'),...
  x , stblpdf(x,1.5,beta,gam,delta,'quick') )
axis([-5 500 0 .6]);
title('Skewed \alpha-stable densities, \beta = 0.5,\gamma = 1, \delta = 0');
legend('\alpha = 0.5',...
    '\alpha = 0.75',...
    '\alpha = 1.0',...
    '\alpha = 1.25',...
    '\alpha = 1.5' )